Navegando de item para contrato
analytics-ufcg/ta-de-pe pull request #386
Opened 2021-08-09 21:28 UTC by felipesqra

2021-08-09 23:45 UTC, gileadekelvin requested changes
Alguns erros de build precisam ser corrigidos. [pipeline](https://github.com/analytics-ufcg/ta-de-pe/runs/3285020722)
![image](https://user-images.githubusercontent.com/10724115/128787912-ae7469e5-836f-44a0-89b3-d168906f37c4.png)

2021-08-09 23:45 UTC, gileadekelvin commented on client/src/app/itens/info-item/info-item.component.html
> +              target="_blank">
Deve ser aberto numa nova aba mesmo?

2021-08-09 23:45 UTC, gileadekelvin commented
A nova informação de contrato e o link funcionou de boas! @felipesqra

2021-08-10 18:40 UTC, felipesqra commented on client/src/app/itens/info-item/info-item.component.html
> +              target="_blank">
Não Gile, acredito que passou despercebido, vou alterar

2021-08-10 22:08 UTC, gileadekelvin approved these changes

2021-08-10 22:08 UTC, merged